version = 0.1
[default.deploy.parameters]
stack_name = "image-gen-infra"
resolve_s3 = true
s3_prefix = "image-gen-infra"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"image-gen\""
image_repositories = []
