AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Infra for Image Generator

Parameters:
  AppName:
    Type: String
    Description: Name of the application
  # AdminEmail:
  #   Type: String
  #   Description: Email address for adminstrator

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AppName}-UserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireUppercase: true
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub ${AppName}-UserPoolClient
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      # AllowedOAuthFlowsUserPoolClient: true
      # AllowedOAuthFlows:
      #   - code
      #   - implicit
      # AllowedOAuthScopes:
      #   - email
      #   - openid
      #   - profile

  BedrockAPI:
    Type: AWS::Serverless::Api
    Name: !Sub ${AppName}-Bedrock-Api
    Properties:
      StageName: Prod
      ApiKeySourceType: HEADER
      BinaryMediaTypes:
        - "*/*"
      EndpointConfiguration:
        Type: REGIONAL
        Name: !Ref bedrockAPI

  BedrockAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        imagePath:
          Type: Api
          Properties:
            Path: /image
            Method: post
            RestApiId: !Ref bedrockAPI
      Runtime: python3.10
      Handler: app.lambda_handler
      CodeUri: src/
      Timeout: 90
      FunctionName: !Sub ${AppName}-Bedrock-Function
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: LambdaBedrockPolicy
              Effect: Allow
              Action:
                - "bedrock:ListFoundationModels"
                - "bedrock:GetFoundationModel"
                - "bedrock:InvokeModel"
                - "bedrock:InvokeModelWithResponseStream"
                - "bedrock:CreateModelCustomizationJob"
                - "bedrock:GetModelCustomizationJob"
                - "bedrock:GetFoundationModelAgreementAvailability"
                - "bedrock:ListModelCustomizationJobs"
                - "bedrock:StopModelCustomizationJob"
                - "bedrock:GetCustomModel"
                - "bedrock:ListCustomModels"
                - "bedrock:DeleteCustomModel"
                - "bedrock:CreateProvisionedModelThroughput"
                - "bedrock:UpdateProvisionedModelThroughput"
                - "bedrock:GetProvisionedModelThroughput"
                - "bedrock:DeleteProvisionedModelThroughput"
                - "bedrock:ListProvisionedModelThroughputs"
                - "bedrock:ListTagsForResource"
                - "bedrock:UntagResource"
                - "bedrock:TagResource"
                - "bedrock:AcceptAcknowledgement"
                - "bedrock:GetModelPermission"
                - "bedrock:GetModelInvocationLogging"
                - "bedrock:PutModelInvocationLogging"
                - "bedrock:CreateFoundationModelAgreement"
                - "bedrock:DeleteFoundationModelAgreement"
                - "bedrock:ListFoundationModelAgreementOffers"
              Resource: "*"
